// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserDeletedNotifier is an autogenerated mock type for the UserDeletedNotifier type
type UserDeletedNotifier struct {
	mock.Mock
}

type UserDeletedNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *UserDeletedNotifier) EXPECT() *UserDeletedNotifier_Expecter {
	return &UserDeletedNotifier_Expecter{mock: &_m.Mock}
}

// NotifyUserDeleted provides a mock function with given fields: ctx, id
func (_m *UserDeletedNotifier) NotifyUserDeleted(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserDeletedNotifier_NotifyUserDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyUserDeleted'
type UserDeletedNotifier_NotifyUserDeleted_Call struct {
	*mock.Call
}

// NotifyUserDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserDeletedNotifier_Expecter) NotifyUserDeleted(ctx interface{}, id interface{}) *UserDeletedNotifier_NotifyUserDeleted_Call {
	return &UserDeletedNotifier_NotifyUserDeleted_Call{Call: _e.mock.On("NotifyUserDeleted", ctx, id)}
}

func (_c *UserDeletedNotifier_NotifyUserDeleted_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserDeletedNotifier_NotifyUserDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserDeletedNotifier_NotifyUserDeleted_Call) Return(_a0 error) *UserDeletedNotifier_NotifyUserDeleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserDeletedNotifier_NotifyUserDeleted_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *UserDeletedNotifier_NotifyUserDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserDeletedNotifier creates a new instance of UserDeletedNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserDeletedNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserDeletedNotifier {
	mock := &UserDeletedNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
