// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dohernandez/faceit/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserUpdatedNotifier is an autogenerated mock type for the UserUpdatedNotifier type
type UserUpdatedNotifier struct {
	mock.Mock
}

type UserUpdatedNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *UserUpdatedNotifier) EXPECT() *UserUpdatedNotifier_Expecter {
	return &UserUpdatedNotifier_Expecter{mock: &_m.Mock}
}

// NotifyUserUpdated provides a mock function with given fields: ctx, id, info
func (_m *UserUpdatedNotifier) NotifyUserUpdated(ctx context.Context, id uuid.UUID, info model.UserInfo) error {
	ret := _m.Called(ctx, id, info)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UserInfo) error); ok {
		r0 = rf(ctx, id, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserUpdatedNotifier_NotifyUserUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyUserUpdated'
type UserUpdatedNotifier_NotifyUserUpdated_Call struct {
	*mock.Call
}

// NotifyUserUpdated is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - info model.UserInfo
func (_e *UserUpdatedNotifier_Expecter) NotifyUserUpdated(ctx interface{}, id interface{}, info interface{}) *UserUpdatedNotifier_NotifyUserUpdated_Call {
	return &UserUpdatedNotifier_NotifyUserUpdated_Call{Call: _e.mock.On("NotifyUserUpdated", ctx, id, info)}
}

func (_c *UserUpdatedNotifier_NotifyUserUpdated_Call) Run(run func(ctx context.Context, id uuid.UUID, info model.UserInfo)) *UserUpdatedNotifier_NotifyUserUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.UserInfo))
	})
	return _c
}

func (_c *UserUpdatedNotifier_NotifyUserUpdated_Call) Return(_a0 error) *UserUpdatedNotifier_NotifyUserUpdated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserUpdatedNotifier_NotifyUserUpdated_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.UserInfo) error) *UserUpdatedNotifier_NotifyUserUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserUpdatedNotifier creates a new instance of UserUpdatedNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUpdatedNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUpdatedNotifier {
	mock := &UserUpdatedNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
